### ISSUE TITLE
Duplicate relation types when adding environments in Umbraco Cloud

### ISSUE THREAD

**Issue by skttl** [dawoe/umbraco-nexu#17]
When I add a dev environment for an Umbraco Cloud project, the dev environment creates the relation types, before it syncs the already created relation types from live. This causes a naming conflict.

I think it happens because Nexu will create the relation types if missing.

A suggestion could be to make a configuration setting, telling the Nexu installer, that it has already been installed, and shouldn't create the relation types regardless of them existing in the solution at the moment.

**Comment by dawoe** [comment]
This issue is fixed in v1.3.0

**Comment by skttl** [comment]
That's fantastic Dave! #h5yr
