### ISSUE TITLE
Umbraco Cloud: Some artifacts collide on unique identifiers.

### ISSUE THREAD

**Issue by sebastiandammark** [dawoe/umbraco-nexu#20]
Umbraco version 7.7.7 (Umbraco Cloud)
Assembly: 1.0.6554.23584
Nexu: 1.3.0
Both Development and Live are running Nexu 1.3.0.

When deploying from Development to Live I get this error: Umbraco Cloud: Some artifacts collide on unique identifiers.

[https://gist.github.com/anonymous/cbade01e7228669ce5af91af35966ee1](https://gist.github.com/anonymous/cbade01e7228669ce5af91af35966ee1)

Everything in the GIST is copy/paste directly from umbraco.io

The biggest problem is that only file changes are deployed to Live environment.
Any new datatypes, doctype or property changes are not visible on the Live site.

So now it's not possible for me to deploy the the Live site.

I've tried to uninstall Nexu, but that just made it worse.
The package doesn't clean up after itself and still refers to /App_Plugins/Nexu/views/dashboard.html in the Developer Dashboard and the relations are still there.

**Comment by dawoe** [comment]
Hi Sebastina,

I replied on the forum : https://our.umbraco.org/projects/backoffice-extensions/nexu/questions-suggestions-bugs/89680-umbraco-cloud-some-artifacts-collide-on-unique-identifiers

**Comment by sebastiandammark** [comment]
That fixed it
