### ISSUE TITLE
Make the NexuService public?

### ISSUE THREAD

**Issue by vonbv** [dawoe/umbraco-nexu#37]
I asked [this](https://our.umbraco.com/projects/backoffice-extensions/nexu/questions-suggestions-bugs/93361-using-getnexurelationsforcontent) question in Our. It would be nice if [the NexuService class](https://github.com/dawoe/umbraco-nexu/blob/develop/Source/Our.Umbraco.Nexu.Core/NexuService.cs) will be marked as public. If that will be the case, my one concern is how will the PropertyParserResolver.Current be instantiated.

**Comment by dawoe** [comment]
Hi @vonbv 

I planned this for release 1.7.0. I will see if I have time to get a beta out today so you can use that in your project

Dave
