### ISSUE TITLE
Archetype parser - System.ArgumentException - Same Key

### ISSUE THREAD

**Issue by f33n3y** [dawoe/umbraco-nexu#39]
Hello,

I am getting the following error when trying to add two archetypes of the same type to a page.

```
ERROR Our.Umbraco.Nexu.Parsers.PropertyParsers.Community.ArchetypeParser - An error occured parsing Archetype property
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)`
```

The error seems to be at https://github.com/dawoe/umbraco-nexu/blob/develop/Source/Our.Umbraco.Nexu.Parsers/PropertyParsers/Community/ArchetypeParser.cs#L116

This occurs because it is using the fieldset aliases as keys in the Dictionary used for the parsers so adding two of the same kind of archetype leads to a duplicate key.

**Comment by dawoe** [comment]
Hi @f33n3y 

Thanks for reporting this. Can you give me the config for this archetype ? That will make it easy for reproducing this.

Dave

**Comment by f33n3y** [comment]
Hi @dawoe 

I'd rather not post the full archetype because it contains a lot of work on behalf of a client and also the archetype is massive. However it is a stock Imulus.Archetype datatype with no changes to any of the settings.

We use the archetype so that CMS users can choose different blocks of content they want on a page. 
There was two archetypes with the alias "Document download" populated on the same page. This archetype had three properties: an Umbraco.MediaPicker2, Umbraco.TrueFalse and an Umbraco.Textbox. When two of these were added to the page, the System.ArgumentException would occur because it would use the "document" alias of the MediaPicker2 as a key in the parsers dictionary:
` var parsers = new Dictionary<string, IPropertyParser>();`

Here is the JSON generated by what was selected/populated in Umbraco. 
`{"fieldsets":[{"properties":[{"alias":"document","value":"umb://media/b2f2122c599d47f8b6eb6a8c8e760e65","propertyEditorAlias":"Umbraco.MediaPicker2","dataTypeId":1401,"dataTypeGuid":"b4e7e38f-9744-481a-8c88-970c8e5cb660","editorState":null,"hostContentType":null},{"alias":"showDividerLine","value":"0","propertyEditorAlias":"Umbraco.TrueFalse","dataTypeId":-49,"dataTypeGuid":"92897bc6-a5f3-4ffe-ae27-f2e7e33dda49","editorState":null,"hostContentType":null},{"alias":"anchor","value":"","propertyEditorAlias":"Umbraco.Textbox","dataTypeId":-88,"dataTypeGuid":"0cc0eba1-9960-42c9-bf9b-60e150b429ae","editorState":null,"hostContentType":null}],"alias":"documentDownload","disabled":false,"id":"636fcf04-9d80-4d23-ae6a-85491451e26b","releaseDate":null,"expireDate":null,"allowedMemberGroups":"","collapse":true,"isValid":true},{"properties":[{"alias":"document","value":"umb://media/950274cf310f46edb6ae1361450305c1","propertyEditorAlias":"Umbraco.MediaPicker2","dataTypeId":1401,"dataTypeGuid":"b4e7e38f-9744-481a-8c88-970c8e5cb660","editorState":null,"hostContentType":null},{"alias":"anchor","value":"anchor","propertyEditorAlias":"Umbraco.Textbox","dataTypeId":-88,"dataTypeGuid":"0cc0eba1-9960-42c9-bf9b-60e150b429ae","editorState":null,"hostContentType":null},{"alias":"showDividerLine","value":"0","propertyEditorAlias":"Umbraco.TrueFalse","dataTypeId":-49,"dataTypeGuid":"92897bc6-a5f3-4ffe-ae27-f2e7e33dda49","editorState":null,"hostContentType":null}],"alias":"documentDownload","disabled":false,"id":"c4df38ce-995c-461f-b2e6-233a0a02240e","releaseDate":null,"expireDate":null,"allowedMemberGroups":"","collapse":true,"isValid":true},{"properties":[{"alias":"introText","value":"<p>with list of links</p>","propertyEditorAlias":"Umbraco.TinyMCEv3","dataTypeId":-87,"dataTypeGuid":"ca90c950-0aff-4e72-b976-a30b1ac57dad","editorState":null,"hostContentType":null},{"alias":"title","value":"text","propertyEditorAlias":"Umbraco.Textbox","dataTypeId":-88,"dataTypeGuid":"0cc0eba1-9960-42c9-bf9b-60e150b429ae","editorState":null,"hostContentType":null},{"alias":"anchor","value":"","propertyEditorAlias":"Umbraco.Textbox","dataTypeId":-88,"dataTypeGuid":"0cc0eba1-9960-42c9-bf9b-60e150b429ae","editorState":null,"hostContentType":null},{"alias":"linkBlocks","value":{"fieldsets":[{"properties":[{"alias":"links","value":{"fieldsets":[{"properties":[{"alias":"linkTitle","value":"image","propertyEditorAlias":"Umbraco.Textbox","dataTypeId":-88,"dataTypeGuid":"0cc0eba1-9960-42c9-bf9b-60e150b429ae","editorState":null,"hostContentType":null},{"alias":"link","value":[{"id":10950,"name":"computer code.jpg","url":"/media/43705/pexels-photo.jpg","isMedia":true,"icon":"icon-picture"}],"propertyEditorAlias":"RJP.MultiUrlPicker","dataTypeId":1067,"dataTypeGuid":"f89f3699-dd04-4021-8cf0-093b8efa3be0","editorState":null,"hostContentType":null}],"alias":"blockLinkItem","disabled":false,"id":"c8e27201-0537-4801-b8f7-9f31b5bfb2bf","releaseDate":null,"expireDate":null,"allowedMemberGroups":""}]},"propertyEditorAlias":"Imulus.Archetype","dataTypeId":1094,"dataTypeGuid":"15bf9300-bf2e-4efa-8880-07161120e76c","editorState":null,"hostContentType":null}],"alias":"linkBlock","disabled":false,"id":"21db40fc-6a68-496c-8d04-4b13313490d2","releaseDate":null,"expireDate":null,"allowedMemberGroups":""}]},"propertyEditorAlias":"Imulus.Archetype","dataTypeId":1093,"dataTypeGuid":"a4211972-9989-499d-b3e7-cafe6a6acff3","editorState":null,"hostContentType":null},{"alias":"showDividerLine","value":"0","propertyEditorAlias":"Umbraco.TrueFalse","dataTypeId":-49,"dataTypeGuid":"92897bc6-a5f3-4ffe-ae27-f2e7e33dda49","editorState":null,"hostContentType":null}],"alias":"textWithListOfLinks","disabled":false,"id":"7a1b2e46-52ee-4e49-8165-afd8524e1586","releaseDate":null,"expireDate":null,"allowedMemberGroups":"","collapse":true,"isValid":true}]}`


You should be able to recreate this by adding two of the same archetype to any page so you get a duplicate key in your parsers dictionary.

Let me know if you need any more info.
Cheers

**Comment by dawoe** [comment]
Hi @f33n3y 

I have been trying to reproduce this. But was not able to.

What version of Nexu are you running ? Because 1.6.0 had a bugfix for archetype : https://github.com/dawoe/umbraco-nexu/issues/35

Dave

**Comment by f33n3y** [comment]
I am using 1.6.0 at the moment.

Cheers

**Comment by f33n3y** [comment]
Ok, please let me know how you get on.

I'm trying that at the moment, I've removed the build in archetype parser and have added my own (which is an exact copy of the Nexu one at the moment) so I can step through the code

**Comment by f33n3y** [comment]
I think I have a workaround for this, not ideal though. Just doing a bit more testing then will post.
Cheers

**Comment by dawoe** [comment]
If you could create a PR that would be awesome !

**Comment by dawoe** [comment]
hi @f33n3y 

Were you able to fix this ?

Dave

**Comment by f33n3y** [comment]
Hi @dawoe 

Apologies for the delay. I've not been scheduled on this in a while. Fix seems to be working however i'm also getting a "collection was modified; enumeration operation may not execute" error in the logs. I plan on investigating that this afternoon to see what is going on before creating any PR.

Cheers

**Comment by dawoe** [comment]
Awesome looking forward to it

**Comment by dawoe** [comment]
Hi @f33n3y 

Any update on this one ?

Dave

**Comment by f33n3y10** [comment]
Hi @dawoe 

I've created a PR for this. Let me know if there are any issues.

Cheers
