### ISSUE TITLE
Duplicate Nexu tab under developer section

### ISSUE THREAD

**Issue by PeterHuys** [dawoe/umbraco-nexu#42]
Developer section shows 2 identical Nexu tabs and dashboard shows 2 tabs (due to upgrade / change of config structure?)

![dashboardconfig](https://user-images.githubusercontent.com/6603304/47155600-6219c580-d2e5-11e8-81ed-1bec03c3d32b.png)

![umbracodevelopernexutabs](https://user-images.githubusercontent.com/6603304/47155601-6219c580-d2e5-11e8-9af8-d95677316a02.png)

**Comment by dawoe** [comment]
Hi @PeterHuys 

I justed both nuget and umbraco package install. Both only install one dashboard in the config file.

How did you get the 2 entries ?

It is safe to delete one by the way.

Dave

**Comment by dawoe** [comment]
Could it also have been a merge conflict at your site. Because I see one is in the startupDeveloperSection..And that should not be there.

dave

**Comment by dawoe** [comment]
Hi @PeterHuys 

Have you been able to track down what caused this ?

Dave

**Comment by PeterHuys** [comment]
Hi Dave,

Can't trace the StartupDeveloperDashboardSection >> Tab, its in there since the initial commit.

The section "Our.Umbraco.Nexu" was added by a NuGet package update. Resolved it for by removing the duplicate section from the config. Maybe because we first used the Umbraco package and then installed the latest NuGet package?

**Comment by dawoe** [comment]
Hi @PeterHuys,

That's probably the issue. Both the Umbraco and Nuget package will try to add the dashboard on install. So that's why you see it twice.

I don't think that is something I can fix easily and not a common way of installing either. So I'm closing this one.

But thanks for reporting.

Dave
