### ISSUE TITLE
Dialog bug on delete since v7.15.3 of Umbraco

### ISSUE THREAD

**Issue by martinjgriffiths** [dawoe/umbraco-nexu#54]
A small bug has bug crept in since the delete dialog was updated to show a confirmation of deleted item(s).

The dialog no longer disappears and now stays on-screen after delete.

I've debugged it and fixed the content-delete.html.  

I'm happy to push the changes if you want them?

**Comment by dawoe** [comment]
Hi @martinjgriffiths 
Would be great if you could create a PR if you already know how to fix it.

Dave

**Comment by martinjgriffiths** [comment]
> Hi @martinjgriffiths
> Would be great if you could create a PR if you already know how to fix it.
> 
> Dave

Submitted pull request #55

**Comment by dawoe** [comment]
Hi @martinjgriffiths 

Your PR has been merged. A new release is rolling out as I am writing this message

**Comment by dawoe** [comment]
Thx for the PR BTW

**Comment by martinjgriffiths** [comment]
> Thx for the PR BTW

Np. Also done my first pull request for Umbraco too! It's been a good day. :-)
