### ISSUE TITLE
MultiUrlPicker not parsed in Umbraco 7.14+

### ISSUE THREAD

**Issue by benjaminc** [dawoe/umbraco-nexu#59]
With Umbraco 7.14, the RJP MultiUrlPicker was pulled into the core, and re-branded as the Umbraco.MultiUrlPicker.  The current RjpMultiUrlPickerParser class would work to parse this updated picker, but the data type checking prevents it from successfully parsing the new type.

**Comment by dawoe** [comment]
Hi @benjaminc 

I have merged the PR and a release is rolling out right now. You can get 1.7.4 from nuget and our.

Thanks for the PR and fix

Dave
