### ISSUE TITLE
DocTypeGridEditorParser not picking up on composition properties

### ISSUE THREAD

**Issue by benjaminc** [dawoe/umbraco-nexu#61]
When you have a document type that has media related via a composition property, and you use that document type in the DocTypeGridEditor, then Nexu does not pick up the relationship between the node which has the grid editor, and the media item picked from the composition property.

**Comment by dawoe** [comment]
Hi @benjaminc 

I merged the PR and released 1.7.5 on our and on nuget. 
Strange this never popped up before. So i guess people are not using compositions in the nested, dtge, ... doctypes....or they just did not notice nexu was not working.

I also checked on the v2 beta release. But the parsing engine works differently so it is not a issue there.

Dave
