### ISSUE TITLE
Can no longer see content app or dashboard

### ISSUE THREAD

**Issue by ismailmayat** [dawoe/umbraco-nexu#63]
I installed the v8 preview using nuget and everything worked fine.  I then came back few days later, no  the dashboard and content app no longer appears.  The assets are being load from package manifest, I see no errors in log or chrome

**Comment by dawoe** [comment]
Hi @ismailmayat 

That is really strange. Does it come back when you restart your server. These should be picked up by Umbraco.

Can you clear out the nexu table and save a content item to see if relations are still being tracked ?

Dave

**Comment by ismailmayat** [comment]
tried restart etc also tried to re install no joy.  Wierd thing is saving items etc it is putting relations into db.  Just not showing the dashboard or the content app

**Comment by dawoe** [comment]
Hmm really strange.

This should be picked up by Umbraco out of the box. Which version of Umbraco are you running on ? I only tested on 8.1

Dave

**Comment by dawoe** [comment]
And another question ? When you try to delete a used item do you see the intercepted delete dialog ?

Dave

**Comment by ismailmayat** [comment]
When i try to delete i get console error:

 Cannot read property 'RelationCheckApi' of undefined

Also when i am logged in and try to hit the api to check status directly i get 404 i.e 

/umbraco/BackOffice/Api/RebuildApi/GetRebuildStatus

**Comment by dawoe** [comment]
Do you have the Our.Umbraco.Nexu.Web dll in your project ?

Which nuget package did you install ?

Dave

**Comment by ismailmayat** [comment]
![Capture](https://user-images.githubusercontent.com/1446692/67853261-0ee86e80-fb06-11e9-879c-ac1dbc212816.PNG)

Hold one where is web? 

Nuget is using 
![image](https://user-images.githubusercontent.com/1446692/67853392-61c22600-fb06-11e9-861d-f1b2769acea6.png)

**Comment by ismailmayat** [comment]
Ok dave, i was using rider and did not install the correct package. I had installed core and parsers but not Our.Umbraco.Nexu I installed that and now all good.
