### ISSUE TITLE
Umbraco 8.5.5 issue deleting media item

### ISSUE THREAD

**Issue by ZacP** [dawoe/umbraco-nexu#72]
Upon deleting a media item without any usage in v8.5.5 with Nexu 2.0.0 or Nexu 2.1.0.158-beta installed, the deletion fails with the error _"Request error: The URL returned a 404 (not found): /umbraco/backoffice/UmbracoApi/Content/DeleteById"_

Note that upon uninstalling Nexu, the deletion works fine.

Steps to reproduce:
1. Install Umbraco 8.5.5
2. Install Nexu 2.0 or 2.1.0.158
3. Go to media and create a new media item of type image
4. Attempt to delete the item and you'll receive the error above

**Comment by dawoe** [comment]
hi @ZacP 

Thanks for reporting the issue. I will try to reproduce and see if I can fix this.

Dave

**Comment by dawoe** [comment]
This has been fixed in version 2.0.1

**Comment by ZacP** [comment]
We confirmed that this is working correctly now. Thanks for the super quick fix!
