### ISSUE TITLE
Umbraco 8.5.5 issue - deleting content item, deletion message doesn't close

### ISSUE THREAD

**Issue by ZacP** [dawoe/umbraco-nexu#73]
Upon deleting a content item in v8.5.5 with Nexu 2.0.0 or Nexu 2.1.0.158-beta installed, the deletion succeeds but the confirmation message never closes.

Note that upon uninstalling Nexu, the deletion works fine.

Steps to reproduce:

1. Install Umbraco 8.5.5
2. Install Nexu 2.0 or 2.1.0.158
3. Go to content and create a new content item
4. Delete the item (we used the right click action in the content tree).  
5. The deletion will succeed but the confirmation message continues showing the "red loading action" and can't be closed (without reloading the page)

![image](https://user-images.githubusercontent.com/5231911/77793679-1b7adf80-7030-11ea-9c5e-a84096210779.png)

**Comment by dawoe** [comment]
Hi @ZacP 

Thanks for reporting this issue. 

Dave

**Comment by dawoe** [comment]
This has been fixed in v2.0.1

**Comment by ZacP** [comment]
We confirmed that this is working correctly now.  Thanks for the super quick fix!  And great job creating this useful package.
