### ISSUE TITLE
Nexu media not working with the latest media picker 8.14.0

### ISSUE THREAD

**Issue by ja0b** [dawoe/umbraco-nexu#77]
Hi Dave!

Just trying out all the possibilities with the package and I just saw that the "related links" content app for the media is not working with the new media picker introduced in 8.14.0.

![image](https://user-images.githubusercontent.com/11311685/123892918-11c1e500-d921-11eb-94a6-3bbc44c04b8d.png)

I used 2 pickers to find out how it works and the related links content app is only showing for the now (Obsolete) Media Picker.

Thanks,
Ale

**Comment by dawoe** [comment]
Hi @ja0b 

Just found this out myself on a recent project. You can expect a new version later today with support for this.

Dave
