### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by etneeko** [dawoe/umbraco-nexu#79]
I have a site with Umbraco7 and when I try to install via the back office it gets halfway through and stops. if I reload the site or the back office I then get an error of: 
Server Error in '/' Application
could not load all types from "Our.Umbraco.Nexu.Web, Version=2.3.0.181, Culture=neutral, PublicToken=null" due to LoaderExceptions, skipping: . system.TypeLoadException on Umbraco.Core.Composing.IUserComposer: Could not load type 'Umbraco.Core.Composing.IUserComposer' from assembly 'Umbraco.Core, version 1.0.7180.24662, Culture=neutral, publicKeyToken=null'.

**Comment by dawoe** [comment]
Hi @etneeko 

Nexu v2 is for Umbraco V8. For V7 you can use https://www.nuget.org/packages/Our.Umbraco.Nexu/1.7.5

Dave

**Comment by etneeko** [comment]
@dawoe ah thank you I'll give it a go, thank you for getting back to me.
