### ISSUE TITLE
No confirmation when delete from media folder

### ISSUE THREAD

**Issue by janvanhelvoort** [dawoe/umbraco-nexu#8]
Hi Dave

If you delete a item or multiple items from a media folder, the confirmation view isn't displayed and the item(s) got deleted

![capture](https://cloud.githubusercontent.com/assets/5024929/24706937/f334763e-1a11-11e7-9981-7a9074837ae9.PNG)

**Comment by dawoe** [comment]
I found the reason why this happens. This delete button doesn't trigger the normal dialog...but just shows a confirm message. Will see if I can fix it and which versions this fix needs to be applied in. In 7.3 this function is not available

**Comment by dawoe** [comment]
This is not able to be fixed. To work around you can disable the bulk actions on the list view
